// Status lines for the home page's "now" line, keyed by time slot.
// To add a line, put it in backticks on its own row inside the right slot, followed by a comma.
// Every slot needs at least one line. Avoid backticks and ${ inside a line.
// fallback is only used when a slot (and the pool it borrows from) has no lines.
const LINES = {
    weekdayEarly: [
        `Negotiating with a V60. The V60 is winning.`,
        `Awake, technically.`,
        `Grinding beans. Mentally also grinding.`,
        `Waiting for the kettle to hit 94°C. Precisely.`,
        `Reading the news. Regretting it slightly.`,
        `Booting up. Slower than the home server.`,
        `First coffee. Opinions available after the second.`,
        `Watching the bloom. Coffee, not flowers.`,
        `Inbox still closed. Protecting the peace a little longer.`,
        `Checking what the AI industry did overnight. Quite a lot, apparently.`,
        `Cold kitchen, warm cup.`,
    ],
    weekdayMorning: [
        `In a meeting, probably about another meeting.`,
        `Thinking one step ahead. Two if the coffee was good.`,
        `Making sure nobody's software subscription surprises them today.`,
        `Turning "we should" into "we will."`,
        `Drawing boxes and arrows. Important boxes. Serious arrows.`,
        `Aligning four countries' worth of opinions before lunch.`,
        `Writing a document that will save a meeting. Hopefully.`,
        `Saying "let me check with the vendor." Checking with the vendor.`,
        `Rewriting a backlog item so a human can understand it.`,
        `Deep in a spreadsheet. Send snacks.`,
        `Finding out which of four countries meant something else.`,
        `Asking "who owns this?" and waiting for the silence to end.`,
    ],
    mondayMorning: [
        `Monday. Reading everything that happened while I was away for two days.`,
        `Monday. Coffee first, calendar second.`,
        `Monday. Pretending my inbox is smaller than it is.`,
        `Monday morning. Rebuilding context from Friday's notes.`,
        `Monday. The week hasn't noticed me yet. Keeping it that way.`,
        `Monday. Priorities set. Priorities already changed.`,
    ],
    lunch: [
        `At lunch. The AI industry shipped three things while I chewed.`,
        `Eating. Back when the soup's gone.`,
        `Lunch. Pretending not to read about a new AI model.`,
        `Refuelling. Human needs, unfortunately, still apply.`,
        `Lunch. Phone face down. Mostly.`,
        `Out for a walk. Riga beats any dashboard.`,
        `Lunch. Brain in low-power mode.`,
        `Lunch break. Everyone's discussing AI. So am I.`,
        `Sandwich in one hand, changelog in the other.`,
    ],
    weekdayAfternoon: [
        `Answering a "quick question." It was not quick.`,
        `Translating vendor roadmaps into human language.`,
        `Spotting problems before they become problems. Or at least before they become Monday's problems.`,
        `Asking "what problem are we actually solving?"`,
        `Somewhere between a roadmap and reality.`,
        `Making spreadsheets and vendors agree with each other.`,
        `Fifth coffee. Don't tell anyone.`,
        `Post-lunch dip. Powered by optimism and caffeine.`,
        `Writing the email that prevents three other emails.`,
        `Reading the fine print so someone else doesn't have to.`,
        `Nodding in a call. Already thinking about the next one.`,
        `Explaining licensing. Again. With diagrams.`,
    ],
    fridayAfternoon: [
        `Friday afternoon. Deploying nothing. Promising nothing.`,
        `Friday. Writing tidy notes for a Monday version of me who won't read them.`,
        `Friday afternoon. Officially in "let's pick this up next week" mode.`,
        `Friday. Closing tabs, browser and mental.`,
        `Friday afternoon. Low-risk decisions only.`,
        `Friday. The backlog can wait. It's very good at waiting.`,
        `Friday afternoon. Weekend loading.`,
        `Friday. Leaving things a bit better than Monday found them.`,
    ],
    evening: [
        `Off the clock. Reading AI release notes "for fun."`,
        `Tinkering with the home server. It's fine. It's mostly fine.`,
        `Catching up on AI news. Already behind again.`,
        `Watching a film instead of a changelog. Small victories.`,
        `Reading about gear I definitely don't need.`,
        `Trying the AI tool everyone discovered this afternoon.`,
        `Updating Docker containers nobody asked me to update.`,
        `Dinner first. Release notes after.`,
        `Reading reviews of a camera I already decided not to buy.`,
        `Watching a video about a tool I'll try tomorrow. Maybe.`,
        `Reading home server logs. Surprisingly relaxing.`,
        `Evening walk. No podcast. Bold, I know.`,
    ],
    night: [
        `Checking if the clouds moved. They didn't.`,
        `Looking up. Latvian sky: 80% clouds, 20% hope.`,
        `Checking the cloud forecast like it's a stock ticker.`,
        `Clear skies? Already outside. Cloudy? Already sulking.`,
        `One more tab. Just one.`,
        `Forecast says clear skies next Tuesday. Allegedly.`,
        `Late night. The home server and I are both still up.`,
        `Reading about telescopes. Looking at clouds.`,
        `Reading one last article. It was not the last.`,
        `Night mode on. Brain not so much.`,
    ],
    deepNight: [
        `Asleep. If you're reading this, you should be too.`,
        `Offline. The home server isn't.`,
        `Asleep. Dreaming of cloudless nights.`,
        `Off. Unlike my backup jobs.`,
        `Sleeping. So is Riga.`,
        `Nothing to see here. Unless it's clear, then everything.`,
        `Asleep. The backups have the night shift.`,
        `Zzz. Try again after sunrise.`,
        `Asleep. Or photographing stars. Ask me tomorrow.`,
    ],
    weekend: [
        `Brewing coffee slower than strictly necessary.`,
        `Out with a camera, waiting for light that behaves.`,
        `Trying a new bean. Taking notes like it's a science project.`,
        `Wandering Riga with a camera and no plan.`,
        `Doing absolutely nothing. Professionally.`,
        `Rebuilding something that already worked.`,
        `Market run. Mostly for the coffee.`,
        `Weekend. The alarm clock has the day off too.`,
        `Somewhere in Old Riga, looking for a good shadow.`,
        `Second pour of the morning. Research, obviously.`,
        `Weekend project. Estimated time: wrong.`,
    ],
    sundayEvening: [
        `Sunday evening. Mentally still on the weekend, calendar says otherwise.`,
        `Sunday evening. Quietly planning a week I'll then ignore.`,
        `Sunday. Beans restocked. Monday, not so much.`,
        `Sunday evening. One last film before the week starts.`,
        `Sunday. Charging all devices, including myself.`,
        `Sunday evening. Laptop still closed. For now.`,
    ],
    goldenHour: [
        `Golden hour. Probably outside with a camera.`,
        `Golden hour. Chasing light down a Riga street.`,
        `The sun's going. The camera's out.`,
        `Golden hour. Even concrete looks good now.`,
        `Best light of the day. Outside, obviously.`,
        `Sunset soon. Tripod optional, patience required.`,
    ],
    midsummer: [
        `Midsummer. The sun refuses to set, so neither do I.`,
        `Midsummer. Night is more of a suggestion.`,
        `Midnight and still light. Sleep can wait.`,
        `White nights. The stars are on holiday until August.`,
        `Midsummer. The sky is doing its own thing again.`,
        `Midsummer. Even the home server doesn't know what time it is.`,
    ],
    fallback: [],
};